### ISSUE TITLE
Grainy Output error

### ISSUE THREAD

**Issue by mcbrs1a** [andreimuntean/A3C#3]
Hi I get grainy output of this  nature when visualizing, any ideads 
![figure_1](https://user-images.githubusercontent.com/33153975/33765380-7723f602-dc10-11e7-9890-818468fc8916.png)

**Comment by andreimuntean** [comment]
Thanks for spotting this! That's a new error from OpenAI Gym 0.8. I've now updated the README to say that OpenAI Gym 0.10 is required.
